import jsPDF from 'jspdf';
import 'jspdf-autotable';

export const exportInspectorPDF = (inspector) => {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();

    // --- Header Section ---
    doc.setFillColor(0, 31, 63); // Navy Blue
    doc.rect(0, 0, pageWidth, 40, 'F');

    doc.setTextColor(255, 255, 255);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(22);
    doc.text('SKYTRAIN - OFFICIAL RECORD', 15, 20);

    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text('DIRECTORATE GENERAL OF CIVIL AVIATION | SAFETY OVERSIGHT SYSTEM', 15, 30);

    // --- Personnel Info ---
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text('FLIGHT INSPECTOR PROFILE', 15, 55);

    doc.setDrawColor(0, 212, 255);
    doc.setLineWidth(0.5);
    doc.line(15, 58, 80, 58);

    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.text('NAME:', 15, 70);
    doc.setFont('helvetica', 'normal');
    doc.text(inspector.name.toUpperCase(), 45, 70);

    doc.setFont('helvetica', 'bold');
    doc.text('ID NUMBER:', 15, 78);
    doc.setFont('helvetica', 'normal');
    doc.text(inspector.id, 45, 78);

    doc.setFont('helvetica', 'bold');
    doc.text('ROLE / RANK:', 15, 86);
    doc.setFont('helvetica', 'normal');
    doc.text(inspector.role, 45, 86);

    doc.setFont('helvetica', 'bold');
    doc.text('UNIT:', 15, 94);
    doc.setFont('helvetica', 'normal');
    doc.text(`${inspector.workingUnit} / ${inspector.subdirectorate}`, 45, 94);

    // --- Mandatory Training Table ---
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text('MANDATORY COURSE TRAINING RECORD', 15, 110);

    const mandatoryData = inspector.trainingLog.mandatory.current.map(row => [
        row.code,
        row.name,
        row.provider,
        row.expired,
        'VALID'
    ]);

    doc.autoTable({
        startY: 115,
        head: [['CODE', 'COURSE NAME', 'PROVIDER', 'EXPIRY DATE', 'STATUS']],
        body: mandatoryData,
        headStyles: { fillColor: [0, 212, 255], textColor: [0, 0, 0], fontStyle: 'bold' },
        styles: { fontSize: 8, cellPadding: 3 },
        margin: { left: 15, right: 15 }
    });

    // --- Non-Mandatory Training Table ---
    let finalY = doc.lastAutoTable.finalY + 15;

    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text('ADDITIONAL QUALIFICATIONS (NON-MANDATORY)', 15, finalY);

    const nonMandatoryData = inspector.trainingLog.nonMandatory.map(row => [
        row.name,
        row.provider,
        row.date
    ]);

    doc.autoTable({
        startY: finalY + 5,
        head: [['COURSE NAME', 'COLLEGE / PROVIDER', 'COMPLETION DATE']],
        body: nonMandatoryData,
        headStyles: { fillColor: [241, 196, 15], textColor: [0, 0, 0], fontStyle: 'bold' },
        styles: { fontSize: 8, cellPadding: 3 },
        margin: { left: 15, right: 15 }
    });

    // --- Footer Section ---
    const totalPages = doc.internal.getNumberOfPages();
    for (let i = 1; i <= totalPages; i++) {
        doc.setPage(i);
        doc.setFontSize(8);
        doc.setTextColor(150);
        doc.text(`Generated by SkyTrain System [v2.4] | Timestamp: ${new Date().toLocaleString()}`, 15, 285);
        doc.text(`Page ${i} of ${totalPages}`, pageWidth - 30, 285);
    }

    doc.save(`SKYTRAIN_RECORD_${inspector.id}.pdf`);
};
